CREATE DATABASE debug_quest;

CREATE TABLE musicals (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    composer VARCHAR(255),	
    premiereDate Date,
    synopsis INT(40),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatmusicalsed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
